services:
  - type: web
    name: linkedin-job-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app
    envVars:
      - key: FLASK_ENV
        value: production
