// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kexvmllymsvjjthnvrwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtleHZtbGx5bXN2amp0aG52cndkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg0MTYyMjYsImV4cCI6MjA0Mzk5MjIyNn0.eWXV_988GYRcwZF5PWx-iQvjm50zwiknBAnxvLDPU_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);